### ISSUE TITLE
aux

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#12]
https://github.com/Unrealf1/Text_Generator/blob/1659089b281fb609859ad857ed634a8a2172e5a7/Train.py#L10

что это значит?

**Comment by Unrealf1** [comment]
Дело в том, что в Windows это зарезервированное имя файла, которое обозначает устройство. И при попытке создать фаил с таким названием и любым расшерением программа аварийно завершается.
