### ISSUE TITLE
defaultdict

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#13]
https://github.com/Unrealf1/Text_Generator/blob/1659089b281fb609859ad857ed634a8a2172e5a7/Train.py#L12-L16

https://github.com/Unrealf1/Text_Generator/blob/1659089b281fb609859ad857ed634a8a2172e5a7/Train.py#L19-L22

чтобы не делать таких проверок, используй defaultdict вместо обычного dict. Тогда эти функции вырождаются в 1 строчку, и смысла нет их оставлять

**Comment by Unrealf1** [comment]
Сделал
