### ISSUE TITLE
названия

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#18]
https://github.com/Unrealf1/Text_Generator/blob/a2d1943c71740dcb246383767ef42c6a5ee2cff5/Train.py#L27
во-первых, название в одну большую букву - это не по code style. Во-вторых, оно ничего не говорит

**Comment by Unrealf1** [comment]
Переделал

**Comment by kuzmichevdima** [comment]
https://github.com/Unrealf1/Text_Generator/blob/9761e2541a1f30cf9dcbf0dca300320088b755e2/Train.py#L39-L40

**Comment by Unrealf1** [comment]
Переделал
