### ISSUE TITLE
стены кода

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#19]
https://github.com/Unrealf1/Text_Generator/blob/a2d1943c71740dcb246383767ef42c6a5ee2cff5/Train.py#L60

68 строк. Нужно разбить на логические части и вынести в функции

**Comment by kuzmichevdima** [comment]
https://github.com/Unrealf1/Text_Generator/blob/a2d1943c71740dcb246383767ef42c6a5ee2cff5/Generate.py#L7
50 строк. То же самое сделать

**Comment by kuzmichevdima** [comment]
https://github.com/Unrealf1/Text_Generator/blob/9761e2541a1f30cf9dcbf0dca300320088b755e2/Train.py#L71-L161

90 строк

**Comment by kuzmichevdima** [comment]
в generate.py вообще все в main написано (60 строк), что недопустимо.

**Comment by kuzmichevdima** [comment]
Суть в том, что на текущий момент из-за этих стен кода очень сложно понять, что происходит в коде

**Comment by Unrealf1** [comment]
Исправил
