### ISSUE TITLE
сокращение

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#21]
https://github.com/Unrealf1/Text_Generator/blob/a2d1943c71740dcb246383767ef42c6a5ee2cff5/Generate.py#L43-L50

очень много лишних действий. poss_word - это просто .keys(), possibility - это просто .values(), сумма считается в 1 строку с использованием sum

**Comment by Unrealf1** [comment]
Но poss_word и possibility инициализируются в этом месте. Ведь нельзя брать .keys() или .values() от файла.

**Comment by kuzmichevdima** [comment]
Согласен, невнимательно прочитал. У многих была такая проблема просто
