### ISSUE TITLE
магическая константа

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#22]
https://github.com/Unrealf1/Text_Generator/blob/9761e2541a1f30cf9dcbf0dca300320088b755e2/Train.py#L170

**Comment by Unrealf1** [comment]
Исправил

**Comment by kuzmichevdima** [comment]
еще одна:
https://github.com/Unrealf1/Text_Generator/blob/52c363e3edcfc6d188833deab841af327191d68f/Train.py#L70

такие параметры лучше вынести в опциональные аргументы запуска Train.py

**Comment by Unrealf1** [comment]
Исправил
