### ISSUE TITLE
бесконечно долго работает

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#23]
Я пытаюсь запустить вот так:
python3 Train.py --input_dir ../small_test_only/ --model model
работает бесконечно долго. Папка small_test_only содержит притом только 1 маленький тест.

**Comment by Unrealf1** [comment]
Параметры вводятся в следующей строке
![default](https://user-images.githubusercontent.com/36414426/39969545-03287718-56e6-11e8-8482-70956c6648bd.png)

**Comment by Unrealf1** [comment]
я это исправил
