### ISSUE TITLE
разная логика для случая stdout/файл

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#25]
https://github.com/Unrealf1/Text_Generator/blob/52c363e3edcfc6d188833deab841af327191d68f/Generate.py#L73-L76

https://github.com/Unrealf1/Text_Generator/blob/52c363e3edcfc6d188833deab841af327191d68f/Generate.py#L80-L83

намного проще просто один раз перенаправить stdout в файл, если это нужно

**Comment by Unrealf1** [comment]
Это критично?

**Comment by kuzmichevdima** [comment]
Если ревью сдать не хочешь, то не критично

**Comment by Unrealf1** [comment]
Переделал
