### ISSUE TITLE
вывод по 1 слову

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#26]
https://github.com/Unrealf1/Text_Generator/blob/52c363e3edcfc6d188833deab841af327191d68f/Generate.py#L81

во-первых, это долго. Во-вторых, так получится 1 длинная строка из слов, а не подобие текста

**Comment by Unrealf1** [comment]
У меня работает довольно быстро. А конец строки я ставлю, когда не находится следующего слова

**Comment by kuzmichevdima** [comment]
1) генерация у тебя работает примерно в 10 раз медленнее других, но это не так важно
2) 1 длинная строка - это не текст. Я сейчас сгенерил для -l 10000 строку, и там ни одного \n не было. Нужно разбивать слова на строки каким-то адекватным образом

**Comment by Unrealf1** [comment]
Длинную строку исправил: добавил аргумент, который позволяет указать длину абзаца
Теперь сохраняю слова в список и вывожу разом
