### ISSUE TITLE
Волшебная константа

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#3]
https://github.com/Unrealf1/Text_Generator/blob/26a2d2d126bbc0389173c5899361fd6ce3e22fa0/Train.py#L52

константы нужно выносить +  правильно называть (см code style)

**Comment by Unrealf1** [comment]
Ну, это опциональная вещь. Просто решил ускорить считывание. То есть теперь можно и не по одной строчке читать, но в оперативке много не храним гарантированно

**Comment by Unrealf1** [comment]
Исправил
