### ISSUE TITLE
фиксированные параметры

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#4]
https://github.com/Unrealf1/Text_Generator/blob/26a2d2d126bbc0389173c5899361fd6ce3e22fa0/Train.py#L72-L73

https://github.com/Unrealf1/Text_Generator/blob/26a2d2d126bbc0389173c5899361fd6ce3e22fa0/Generate.py#L25-L26

если тебе нужно для проверки все время запускать свой скрипт определенным образом, сделай bash скрипт из 1 строчки с запуском. Не нужно в коде прописывать костыли

**Comment by Unrealf1** [comment]
Убрал
