### ISSUE TITLE
список файлов

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#5]
https://github.com/Unrealf1/Text_Generator/blob/26a2d2d126bbc0389173c5899361fd6ce3e22fa0/Train.py#L77-L83

это все нужно переписать в одну строчку красивым образом. Для склейки путей используй os.path.join(), я на семинаре говорил про то, чем это лучше ручной склейки

**Comment by Unrealf1** [comment]
Переписал
