### ISSUE TITLE
==None

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#6]
https://github.com/Unrealf1/Text_Generator/blob/26a2d2d126bbc0389173c5899361fd6ce3e22fa0/Generate.py#L40

здесь и в других местах заменить ==None на is None. Почему так лучше:
https://stackoverflow.com/questions/14247373/python-none-comparison-should-i-use-is-or

**Comment by Unrealf1** [comment]
Исправил
