### ISSUE TITLE
рандом

### ISSUE THREAD

**Issue by kuzmichevdima** [Unrealf1/Text_Generator#7]
https://github.com/Unrealf1/Text_Generator/blob/26a2d2d126bbc0389173c5899361fd6ce3e22fa0/Generate.py#L5-L13

давай использовать готовую функцию numpy.random.choice с параметром p (посмотри документацию, там все просто). Не нужно реализовывать свои велосипеды

почему я вижу в другом репозитории тот же самый код с теми же названиями?

```
def weighted_choice(choices): 
     total = sum(choices[c] for c in choices) 
     r = random.uniform(0, total) 
     upto = 0 
     for c in choices: 
         if upto + choices[c] >= r: 
             return c 
         upto += choices[c] 
     assert False, "Shouldn't get here" 
```

**Comment by Unrealf1** [comment]
Переделал рандом.

Код такой же, потому что он был показан в качестве примера хорошего рандома в ТЗ.
